---
- name: Applica configurazione ai server
  hosts: all
  become: true

  vars:
    # Dominio pubblico su cui l'applicazione è pubblicata
    # Questo dominio deve risolvere all'host su cui viene
    # eseguito il container di frontend (nginx-letsencrypt).
    app_domain: "spid-test.spc-app1.teamdigitale.it"

    # L'entity ID ha come valore di default quello di
    # app_domain qui sopra definito. In caso sia necessario
    # può esserne fatto l'override tramite la seguente variabile:
    shibboleth_entityid: "spid.agid.gov.it"

    # Riferimento email dell'amministratore
    admin_email: "federico@teamdigitale.governo.it"

    # Path sul server della chiave e del certificato SAML
    # del service provider (questi path vengono montati
    # all'interno del container shibboleth-nginx).
    shibboleth_credentials_key: "/etc/ssl/private/spid-agid-certs/spid-agid-signature.key"
    shibboleth_credentials_cert: "/etc/ssl/private/spid-agid-certs/spid-agid-signature.cer"

    # Backend del layer applicativo.
    # Attualmente corrisponde al container applicativo, ma
    # può essere un host esterno raggiungibile dal server di
    # frontend.
    app_backend_url: "http://app-backend:8080"

    # Prefisso applicativo protetto da autenticazione SPID.
    app_prefix: "/app"

  roles:
    - name: docker

    - name: app-backend
      tags: app-backend

    - name: shibboleth
      tags: shibboleth
      app_backend_container: app-backend

    - name: letsencrypt
      tags: letsencrypt
      shibboleth_container: shibboleth-nginx
