---
- name: "Make sure /opt/docker-nginx-letsencrypt exist"
  file: path=/opt/docker-nginx-letsencrypt state=directory owner=root

- name: "Create docker-nginx-letsencrypt config"
  template: src=docker-nginx-letsencrypt.conf.j2 dest=/opt/docker-nginx-letsencrypt/nginx/default.conf owner=root

- name: "Make sure nginx-letsencrypt container is restarted"
  docker_container:
    name: nginx-letsencrypt
    image: bradjonesllc/docker-nginx-letsencrypt
    recreate: true
    published_ports:
      - "80:80"
      - "443:443"
    links:
      - "{{ shibboleth_container }}:{{ shibboleth_container }}"
    volumes:
      - "/opt/docker-nginx-letsencrypt/ssl/dhparam:/etc/ssl/dhparam"
      - "/opt/docker-nginx-letsencrypt/letsencrypt:/etc/letsencrypt"
      - "/opt/docker-nginx-letsencrypt/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    env:
      CERTS: "{{ app_domain }}"
      EMAIL: "{{ admin_email }}"
