---
- name: Applica configurazione ai server
  hosts: all
  become: true

  vars:
    app_domain: "spid-test.spc-app1.teamdigitale.it"
    admin_email: "federico@teamdigitale.governo.it"
    app_backend_url: "http://app-backend:8080"
    app_prefix: "/app"
    
  roles:
    - name: docker

    - name: app-backend
      tags: app-backend

    - name: shibboleth
      tags: shibboleth
      shibboleth_credentials_key: "/etc/ssl/private/spid-agid-certs/spid-agid-signature.key"
      shibboleth_credentials_cert: "/etc/ssl/private/spid-agid-certs/spid-agid-signature.cer"
      app_backend_container: app-backend

    - name: letsencrypt
      tags: letsencrypt
      shibboleth_container: shibboleth-nginx
